/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { api } from '../lib/api';
export interface HelloResponse {
  message: string;
}

export const getFastAPI = () => {
/**
 * シンプルなテスト用エンドポイント。Helloメッセージを返す。
 * @summary 挨拶を返すAPI
 */
const getHello = (

 ) => {
      return api<HelloResponse>(
      {url: `/hello`, method: 'GET'
    },
      );
    }

return {getHello}};
export type GetHelloResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['getHello']>>>
